"""add deck table

Revision ID: 87cfe6e572a9
Revises: 4169148d3f80
Create Date: 2023-10-20 23:30:10.907959

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "87cfe6e572a9"
down_revision = "4169148d3f80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deck",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("deck", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_deck_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_deck_name"), ["name"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deck", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_deck_name"))
        batch_op.drop_index(batch_op.f("ix_deck_created_at"))

    op.drop_table("deck")
    # ### end Alembic commands ###
