"""new field about me user field

Revision ID: aaa44fb52cc5
Revises: 87cfe6e572a9
Create Date: 2023-10-21 07:05:25.241233

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aaa44fb52cc5"
down_revision = "87cfe6e572a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("about_me", sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("about_me")

    # ### end Alembic commands ###
