#!/bin/bash

set -e
if [[ -e .env ]]; then
    source .env
fi

export FLASK_APP=ziho.py

HOST="--host=0.0.0.0"
DEBUG="--debug"

run() {
    local debug="$DEBUG"
    local host=""
    if [ -n "$LOCAL_ENV" ] && [ "$LOCAL_ENV" = "prod" ]; then
        debug=""
    fi
    if [[ -n "$DOCKER_ENV" ]]; then
        host="$HOST"
    fi
    flask run ${host:+"$host"} ${debug:+"$debug"}
}

if [ "$LOCAL_ENV" = "prod" ] && [ -z "$DOCKER_ENV" ]; then
    sass ziho/static/scss/main.scss ziho/static/css/main.css 2>/dev/null
elif [ -z "$DOCKER_ENV" ]; then
    sass --watch ziho/static/scss/main.scss ziho/static/css/main.css &
fi

run
