#!/bin/bash

set -x
if [[ -e .env ]]; then
    source .env
fi

export FLASK_APP=ziho_app.py

version=1.77.5

if [[ -z "$DOCKER_ENV" ]]; then
    pip install -r requirements.txt
    # Doesn't work with docker
    tarball="dart-sass-$version-linux-x64.tar.gz"
else
    tarball="dart-sass-$version-linux-x64-musl.tar.gz"
fi

# Setup db
flask db init 2>/dev/null
flask db migrate
flask db upgrade

CWD="$(pwd)"
mkdir -p "bin/sass"
tmpdir="$(mktemp -d)"
trap "rm -r $tmpdir" EXIT
cd "$tmpdir"

curl -fLO --retry 3 "https://github.com/sass/dart-sass/releases/download/$version/$tarball"
tar -xf "$tarball" --strip-components=1 -C "$CWD/bin/sass"

"$CWD"/bin/sass/sass --no-source-map --style compressed "$CWD"/ziho/static/scss/main.scss "$CWD"/ziho/static/css/main.css

